---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04-docker
    driver_config:
      image: ubuntu-upstart:14.04
      disable_upstart: false
      run_command: '/sbin/init'
  - name: ubuntu-16.04-docker
    driver_config:
      image: ubuntu:16.04
      run_command: '/sbin/init'
      provision_command:
        - apt-get install -y dbus
        - systemctl set-default multi-user.target
  - name: ubuntu-18.04-docker
    driver_config:
      image: ubuntu:18.04
      run_command: '/sbin/init'
      provision_command:
        - apt-get install -y dbus
        - systemctl set-default multi-user.target
  - name: debian-8-docker
    driver_config:
      image: debian:8
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - apt-get install -y dbus
        - systemctl set-default multi-user.target
  - name: debian-9-docker
    driver_config:
      image: debian:9
      disable_upstart: false
      run_command: '/lib/systemd/systemd'
      provision_command:
        - apt-get install -y dbus
        - systemctl set-default multi-user.target
  - name: centos-6-docker
    driver_config:
      image: centos:6
      run_command: '/sbin/init'
  - name: centos-7-docker
    driver_config:
      image: centos:7
      run_command: '/lib/systemd/systemd'
      provision_command:
        - yum install -y dbus
        - systemctl set-default multi-user.target
  - name: fedora-28-docker
    driver_config:
      image: fedora:28
      run_command: '/lib/systemd/systemd'
      provision_command:
        - dnf install -y dbus
        - systemctl set-default multi-user.target
  - name: fedora-29-docker
    driver_config:
      image: fedora:29
      run_command: '/lib/systemd/systemd'
      provision_command:
        - dnf install -y dbus
        - systemctl set-default multi-user.target
  - name: fedora-30-docker
    driver_config:
      image: fedora:30
      run_command: '/lib/systemd/systemd'
      provision_command:
        - dnf install -y dbus libxcrypt-compat
        - systemctl set-default multi-user.target
  - name: opensuse-leap-42-docker
    driver_config:
      image: opensuse/leap:42.3
      run_command: '/bin/systemd'
      provision_command:
        - zypper install -y dbus-1 tar gzip
        - systemctl enable sshd
  - name: amazonlinux-2-docker
    driver_config:
      image: amazonlinux:2
      run_command: '/sbin/init'
      platform: rhel
      provision_command:
        # Hack to make chef_installer.sh detect platform correctly.
        - echo "Amazon Linux 2" > /etc/system-release
        - yum install -y tar

suites:
  - name: default
    run_list:
      - recipe[pgmetrics::default]
    verifier:
      inspec_tests:
        - test/integration/default
