services:
  - docker

language: ruby
cache: bundler
sudo: false
rvm:
- 2.6.0

before_install:
  - gem update --system
  - gem install bundler

bundler_args: "--without kitchen_vagrant"

script: "bundle exec kitchen test ${INSTANCE} --destroy=always"

env:
  matrix:
    - INSTANCE=default-ubuntu-1404-docker
    - INSTANCE=default-ubuntu-1604-docker
    - INSTANCE=default-ubuntu-1804-docker
    - INSTANCE=default-debian-8-docker
    - INSTANCE=default-debian-9-docker
    - INSTANCE=default-centos-6-docker
    - INSTANCE=default-centos-7-docker
    - INSTANCE=default-fedora-28-docker
    - INSTANCE=default-fedora-29-docker
    - INSTANCE=default-opensuse-leap-42-docker
    - INSTANCE=default-amazonlinux-2-docker

jobs:
  include:
    - stage: lint
      script:
        - bundle exec cookstyle --version
        - bundle exec cookstyle .
        - bundle exec foodcritic --version
        - bundle exec foodcritic --contex --epic-fail any .
    - stage: deploy
      if: tag =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$
      script:
        - openssl aes-256-cbc -K $encrypted_f15b1e22caf1_key -iv $encrypted_f15b1e22caf1_iv -in /.travis/dr_agon.pem.enc -out .travis/dr_agon.pem -d
        - bundle exec stove login --username dr_agon --key .travis/dr_agon.pem
        - bundle exec stove --no-git
