name 'pgmetrics'
maintainer 'Kirill Kuznetsov'
maintainer_email 'agon.smith@gmail.com'
license 'Apache-2.0'
description 'Installs pgmetrics binary'
long_description 'Installs pgmetrics binary'
version '0.1.0'
chef_version '>= 12.14' if respond_to?(:chef_version)

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'opensuse'
supports 'opensuseleap'
supports 'redhat'
supports 'suse'
supports 'ubuntu'

issues_url 'https://github.com/dragonsmith/chef-pgmetrics/issues'
source_url 'https://github.com/dragonsmith/chef-pgmetrics'
